# Simple makefile for building and packaging project Armadillo

# Simple makefile for building and packaging project Yaml cpp

library=armadillo
url=https://flow.nti.tul.cz/libraries/armadillo-$(version).tar.xz
base_name=armadillo-$(version)

include ../common_cmake.mk
